### ISSUE TITLE
does not work?

### ISSUE THREAD

**Issue by SHxKM** [AdvocatesInc/django-channels-discord#2]
Hi thanks for making this. I took the example you gave almost 1-to-1 (adjusted `token` and `application` of course), and when `MyDiscordConsumer` is a `SyncConsumer` then this error appears:

```
..../consumers/my_discord_consumer.py:14: RuntimeWarning: coroutine 'DiscordConsumer.send_action' was never awaited
```

And when I try making `MyDiscordConsumer` an `AsyncConsumer` then I get this error:

```
 File "..../site-packages/asgiref/server.py", line 73, in application_send
    raise NotImplementedError("You must implement application_send()")
  You must implement application_send()
```

I'm wondering if this should still work..

**Comment by SHxKM** [comment]
Running through the CLI doesn't work at all either:

```
ModuleNotFoundError: No module named 'my_app'
```

**Comment by MattBroach** [comment]
Hey, sorry you're having issues.  We're running this in production, so I know it works, but the documentation is out of date, and could potentially solve some of your problems.  Here are a few things to note:

1. As you already noted, but the functions in the consumer should all be `async`, including `send_action`.

2. There was a slight change in the structure of the Routers when the library was changed to use Channels 3, which has not been reflected in the docs: consumers now need to be called with `as_asgi`.  So the code from the third step should now read as

    ```python
    from channels.routing import ProtocolTypeRouter
    from myapp.consumers import MyDiscordConsumer

    application = ProtocolTypeRouter({
        'discord': MyDiscordConsumer.as_asgi(),
   })
   ```

3. For the CLI, `my_app` is a placeholder -- it should be the path to your asgi file (usually in the same folder as your settings).  So, for example, if your main project folder is instead `discord_test`, the CLI would instead read:

    ```bash
    channels-discord -t 'MY_LONG_BOT_TOKEN' -a 'discord_test.asgi:my_application'
    ```

Sorry for the outdated docs -- I'll add updating those to my to-do list.  Let me know if the above fixes your issues.

**Comment by SHxKM** [comment]
@MattBroach no need to apologize, you were already kind enough to show some direction. And thanks for the clarificaitons, unfortunately I've already noted `(1)` and `(2)`, and for `(3)` I'm already passing _my_ application's path, but unfortunately can't spin up the CLI. When I copy `cli.py` and invoke it manually it does work, but then I get the error in the OP.

May I ask which version of Django you are running production? maybe that's the issue here..
Thanks again for your help!

**Comment by SHxKM** [comment]
Wait, are you sure it isn't supposed to be:

```
application = ProtocolTypeRouter({
    "channel": ChannelNameRouter(
        {
            "discord": MyDiscordConsumer.as_asgi()
        }
    })
```

?

Hmmmm..

**Comment by MattBroach** [comment]
Hrm, I think you need to have the 'discord' in the top level of the 'ProtocolTypeRouter', because 'discord' is the protocol type -- so I don't think your example would work.  

Right now, we're using:
Django==3.2.6
channels==3.0.4
channels-discord==0.4.0

I'm not sure the django version would have a big effect, but running an older version of the other two would certainly cause issues.  The `ModuleNotFound` error from the CLI does seem to imply that it can't find the asgi app when running the CLI, which may be an issue of setting your PYTHONPATH env variable or running it from the proper folder.  That doesn't explain the `application_send` issue, though...

**Comment by MattBroach** [comment]
I wonder if the issue is still that it's not loading your application properly when running directly.  Since a lot of that stuff is for CLI parsing, a simpler version would be running something like:

```python
from channels_discord.client import ChannelsDiscordClient

from my_project.asgi import application

client = ChannelsDiscordClient(application)
client.run('MY_BOT_TOKEN')
```

What happens when you run something like that (with the proper import path for the asgi object)?

**Comment by SHxKM** [comment]
Hmm, that is surprising. But then if:

```
async_to_sync(channel_layer.send)("discord",  {
            "type": "test.print",
            "action": "dm",
        })
```

Sends over to the `channel` (protocol) named `discord` according to the Channels docs, how would one send to the `discord` protocol? I'm confused. [Reference](https://channels.readthedocs.io/en/stable/topics/worker.html#receiving-and-consumers).

**Comment by SHxKM** [comment]
> ```python
> client = ChannelsDiscordClient(application)
> ```

Runs well. I see the following logs:

```
2022-08-08 23:51:10,536 discord.client DEBUG    Dispatching event socket_event_type
2022-08-08 23:51:10,537 discord.client DEBUG    Dispatching event guild_available
2022-08-08 23:51:12,541 discord.client DEBUG    Dispatching event ready
2022-08-08 23:51:12,542 aioredis     DEBUG    Cancelling waiter (<Future cancelled>, [None, None])
2022-08-08 23:51:12,542 aioredis     DEBUG    Waiter future is already done <Future cancelled>
2022-08-08 23:51:12,543 aioredis     DEBUG    Closed 1 connection(s)
```


But now nothing seems to be received. Do I need to run both a `runworker` instance and a `channels-cli` instance?

So:

1. Django app `runserver`
2. `discord-channels` "CLI"
3. `./manage.py runworker discord`

Or just the first 2?

**Comment by SHxKM** [comment]
The `You must implement application_send()` issue was because I was wrapping the `"discord": {}` in `asgi.py` in `"channel": {}`, so that's now gone.

If I run only Django server + discord-channels instance, nothing happens when I trigger the message sending to the consumer.

If I run Django server + discord-channels + `runworker discord`, when a message is sent the `discord` worker complains about `No application configured for scope type 'channel'`.

I must be doing something wrong...

**Comment by MattBroach** [comment]
Ah, well, channels is a little confusing in this regard.  To answer your second question first -- you shouldn't need the django runserver (unless you are doing something that is also taking HTTP or websocket requests) or runworker.  

So, the way the `ProtocolTypeRouter` works is that it looks at the type in the scope to know where to pass a message.  This is defined in the library when the application is instantiated: https://github.com/AdvocatesInc/django-channels-discord/blob/master/channels_discord/client.py#L27.  So that's why "discord" needs to be at the top level of your `ProtocolTypeRouter`, although you can use other routers inside that -- or it can just be a single consumer.

So, django_channels took me awhile to fully wrap my head around.   We don't want to use runworker/ChannelNameRouter here, because this isn't a background task that the docs are referring to -- it's a Protocol Interface Server, which is a fancy way of saying "something that hooks channels up to another kind of messaging".  Daphne, the main Interface Server for channels, handles the websocket and HTTP protocols, but it doesn't know how to speak discord.  So that's what this library is for.  The runworker/Channel Name Router is meant for running local tasks that don't connect to anything else necessarily (sort of a replacement for something you might use `celery` for).

And yeah, unfortunately, the docs mention how to set up the library but not really how to use it (again, that's on me).  The shortest path to showing that it does something would be to instead change the ready action to post a message, such as:

```python
 MyDiscordConsumer(DiscordConsumer):
    async def ready(self):
        await self.send_action('dm', user_id='SOME_DISCORD_USER_ID', text='your message')
```

To do more complicated interactions, you'd probably want to add a `groups` property to your consumer, and then you could send messages from the shell or elsewhere in your app using `channel_layers.group_send` (as an aside, I _very_ rarely use `channel_layers.send`, because channel names are generated randomly when a connection in is made.  As mentioned about "discord" is the protocol, not the channel_name -- the name if your channel would actually be some random string like `channel_23df23jf`, and you can't know it a priori.  Groups can be more easily defined, though -- see [here] (https://channels.readthedocs.io/en/stable/topics/channel_layers.html#groups))

That was a lot of info, but hopefully it put you on the right track.

**Comment by SHxKM** [comment]
@MattBroach Very much so, appreciated. However, I'm still unable to get it to work, and perhaps I'm missing something very obvious that you'd spot faster:

```python
# asgi.py

application = ProtocolTypeRouter({
    "http": my_app,
    "websocket": AuthMiddlewareStack(
        URLRouter(
            websocket_urlpatterns
        ),
    ),
    "discord": MyDiscordConsumer.as_asgi()
})
```

Taken straight from the example:

```python
# my_discord_consumer.py

class MyDiscordConsumer(DiscordConsumer):
    async def ready(self):
        """
        Optional hook for actions on connection to Discord
        """
        print('You are now connected to discord!')

    def my_custom_message(self):
        """
        Use built-in functions to send basic discord actions
        """
        self.send_action('dm', user_id='SOME_DISCORD_USER_ID', text='your message')
        self.send_action(
            'send_to_channel',
            channel_id='SOME_DISCORD_CHANNEL_ID',
            text='your message'
        )
```

Some `view.py`:

```python

    # the consumer adds itself to the group upon __init__
    channel_layer = channels.layers.get_channel_layer()
    async_to_sync(channel_layer.group_send)("discord",  {
            "type": "my.custom_message"
        })

# or 

    channel_layer = channels.layers.get_channel_layer()
    async_to_sync(channel_layer.send)("discord",  {
            "type": "my.custom_message"
        })

```

My guess it's the invocation by now...

**Comment by SHxKM** [comment]
There must be something with my environment that is different. even the `ready` example you gave isn't really working.

**Comment by SHxKM** [comment]
Presumably the only issue left now is that Django/Daphne aren't registering the consumer. I guess/assume `ChannelsDiscordClient` is ready to roll, but something is still missing.

**Comment by SHxKM** [comment]
Well, I got it to work.

The key is not to add the consumer to a channels' group in the `MyDiscordConsumer`'s own `__init__` method, **nor** add it _directly_ (via `group_add`) in the `DiscordConsumer.ready` method. Those don't work.

But when I added `self.groups = ["channel_name"]` to `MyDiscordConsumer`'s `__init__` method, it worked. `on_discord_ready` got called, found `self.groups`, added the consumer to the group, and the message was received. 

Thanks for all the help @MattBroach! Would love an explanation why adding directly doesn't work, but please don't feel obliged.

**Comment by MattBroach** [comment]
Hey, sorry for the delay, got sucked into some other work.  Could I see an example of your adding directly code?  It _should_ work, although given some other issues, I wonder if there's a problem with `ready` being called correctly.  I can try to dig into it later.

**Comment by SHxKM** [comment]
@MattBroach please don't apologize, you putting this out has already saved me a ton of time. I won't be using the library directly (because I need additional functionality than what `DiscordClient` offers), but it's a great time-saver. Maybe i'll add support for more methods once I implement them myself.

I was just doing the regular Channels thing in the `Consumer`'s `__init__` method:

``` 
# init - since it's sync
async_to_sync(self.channel_layer.group_add)("targetName", self.channel_name)
```

```
# ready method
await self.channel_layer.group_add("targetName", self.channel_name)
```

I've only used `WebSocket` consumers before this one, and there it'd usually be done in `connect`, which doesn't exist on `AsyncConsumer`.

Cheers!

**Comment by MattBroach** [comment]
Hrm, that _should_ work in `ready`, so I'll do a little debugging to make sure that's being called correctly.  Depending on the ordering of things it _may_ not work in `__init__`, since I'm not sure the `self.channel_name` will be available that early.  `ready` essentially replaces `connect` for this consumer, but they should function similarly.  I'll dig into what the issue is there.

`DiscordConsumer` _should_ be extensible to add whatever extra functionality you need (all messages from discord should be passed on to the consumer), but obviously if it's easier to work from scratch, feel free to do so!  Thanks for all the testing of the library.

**Comment by SHxKM** [comment]
> Hrm, that should work in ready, so I'll do a little debugging to make sure that's being called correctly. Depending on the ordering of things it may not work in __init__, since I'm not sure the self.channel_name will be available that early. ready essentially replaces connect for this consumer, but they should function similarly. I'll dig into what the issue is there.

I hope I don't waste your time because I'd missed something :/

> DiscordConsumer should be extensible to add whatever extra functionality you need (all messages from discord should be passed on to the consumer), but obviously if it's easier to work from scratch, feel free to do so! Thanks for all the testing of the library.

Yep, but `DiscordClient` can't (easily/possibly) be extended to, say, send an `Embed` (a Discord thingy) if we want to use the CLI invocation I guess. That of course can be supported in the future in a plethora of ways.
